
source 'https://cdn.cocoapods.org/'
source 'https://github.com/zimub/MySpecs.git'
source 'https://gitlab.playnexx.net/PluginsRepo/pluginlibspecs.git'
use_frameworks!
platform :ios, '13.0'
# 设置所有 Pod 的部署目标
#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#      # 解决 Apple Silicon Mac 模拟器架构冲突
#      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
#    end
#  end
#end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
    # 兼容 xcconfig
    if target.respond_to?(:podfile)
      target.podfile.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
target 'MyTTAd_Example' do
  pod 'MyTTAd', :path => '../'

  target 'MyTTAd_Tests' do
    inherit! :search_paths

    pod 'CleanJSON', '1.0.9'
  end
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['ARCHS'] = 'arm64 x86_64'
#      config.build_settings['VALID_ARCHS'] = 'arm64 x86_64'
##      config.build_settings['EXCLUDED_ARCHS[sdk=iphoneos*]'] = 'armv7 armv7s'
##      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 armv7 armv7s'
#    end
#  end
#end


