use_frameworks!

platform :ios, '12.0'

target 'MyTTAd_Example' do
  pod 'MyTTAd', :path => '../'

  target 'MyTTAd_Tests' do
    inherit! :search_paths

    pod 'CleanJSON', '1.0.9'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = 'arm64 x86_64'
      config.build_settings['VALID_ARCHS'] = 'arm64 x86_64'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphoneos*]'] = 'armv7 armv7s'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 armv7 armv7s'
    end
  end
end
